"""Модель для хранения файлов в кнопках меню

Revision ID: 07771cc840e4
Revises: 2b9d4fa08dc2
Create Date: 2024-09-24 10:15:41.039005
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '07771cc840e4'
down_revision: Union[str, None] = '2b9d4fa08dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'menubuttonfile',
        sa.Column('button_id', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column(
            'file_type',
            sa.Enum('DOCUMENT', 'IMAGE', name='menubuttonfiletype'),
            nullable=False,
        ),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ['button_id'],
            ['menubutton.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('menubuttonfile', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_menubuttonfile_id'), ['id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menubuttonfile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menubuttonfile_id'))

    op.drop_table('menubuttonfile')
    # ### end Alembic commands ###
