"""Смена типа для поля тип файла

Revision ID: 0ef4e5f5d192
Revises: 07771cc840e4
Create Date: 2024-09-24 13:20:28.976868
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0ef4e5f5d192"
down_revision: Union[str, None] = "07771cc840e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("menubuttonfile", schema=None) as batch_op:
        batch_op.alter_column(
            "file_type",
            existing_type=postgresql.ENUM(
                "DOCUMENT", "IMAGE", name="menubuttonfiletype"
            ),
            type_=sa.String(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("menubuttonfile", schema=None) as batch_op:
        batch_op.alter_column(
            "file_type",
            existing_type=sa.String(),
            type_=postgresql.ENUM(
                "DOCUMENT", "IMAGE", name="menubuttonfiletype"
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
