"""Добавил модель кнопки меню бота

Revision ID: 2b9d4fa08dc2
Revises: 2f9fb536b4ef
Create Date: 2024-09-23 12:54:12.880757
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b9d4fa08dc2"
down_revision: Union[str, None] = "2f9fb536b4ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menubutton",
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("content_text", sa.String(), nullable=True),
        sa.Column("content_image", sa.String(), nullable=True),
        sa.Column("content_link", sa.String(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("is_main_menu_button", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["menubutton.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("menubutton", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_menubutton_id"), ["id"], unique=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_id"))

    with op.batch_alter_table("menubutton", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_menubutton_id"))

    op.drop_table("menubutton")
    # ### end Alembic commands ###
