"""Добавил отметку о взятии в работу заявку

Revision ID: 3239b2ee8195
Revises: 5f248c1e23af
Create Date: 2024-10-01 10:07:06.623833
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3239b2ee8195'
down_revision: Union[str, None] = '5f248c1e23af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactrequest', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('in_progress', sa.Boolean(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactrequest', schema=None) as batch_op:
        batch_op.drop_column('in_progress')

    # ### end Alembic commands ###
