"""РАсширил модель пользователя, для создания сотрудников

Revision ID: 5f248c1e23af
Revises: ab8abd9993e5
Create Date: 2024-09-30 19:54:31.594246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f248c1e23af'
down_revision: Union[str, None] = 'ab8abd9993e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_manager', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('telegram_user_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('telegram_user_id')
        batch_op.drop_column('is_manager')

    # ### end Alembic commands ###
