"""Добавил в заявку на обратную связь поле email

Revision ID: 7fa6733117fa
Revises: ba85768f6815
Create Date: 2024-09-27 21:24:08.255495
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fa6733117fa"
down_revision: Union[str, None] = "ba85768f6815"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contactrequest", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(), nullable=False))
        batch_op.add_column(
            sa.Column("contact_via_email", sa.Boolean(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contactrequest", schema=None) as batch_op:
        batch_op.drop_column("contact_via_email")
        batch_op.drop_column("email")

    # ### end Alembic commands ###
