"""Изменил id пользователя телеграм на строковый

Revision ID: ab8abd9993e5
Revises: 5ee7c0cb24c0
Create Date: 2024-09-28 22:03:54.224238
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ab8abd9993e5'
down_revision: Union[str, None] = '5ee7c0cb24c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column(
            'telegram_user_id',
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column(
            'telegram_user_id',
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
