"""Добавил поле, в заявку на обратную связь, указывающее на менеджера, работающего над заявкой

Revision ID: b27a622adf51
Revises: 3239b2ee8195
Create Date: 2024-10-01 10:51:06.614900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27a622adf51'
down_revision: Union[str, None] = '3239b2ee8195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.alter_column('in_progress',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_foreign_key('user_contact_request', 'user', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactrequest', schema=None) as batch_op:
        batch_op.drop_constraint('user_contact_request', type_='foreignkey')
        batch_op.alter_column('in_progress',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###
