"""Добавил модель для запроса обратной связи

Revision ID: e22d4bfe4758
Revises: 0ef4e5f5d192
Create Date: 2024-09-26 15:41:33.863974
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e22d4bfe4758"
down_revision: Union[str, None] = "0ef4e5f5d192"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contactrequest",
        sa.Column("telegram_user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("contact_via_telegram", sa.Boolean(), nullable=False),
        sa.Column("contact_via_phone", sa.Boolean(), nullable=False),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contactrequest", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contactrequest_id"), ["id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contactrequest", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contactrequest_id"))

    op.drop_table("contactrequest")
    # ### end Alembic commands ###
